server:
  port: 11000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

spring.data.orient:
  url: plocal:orientdb/iot
  username: root
  password: hello

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
