server:
  port: 21000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true


#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
